// build-components/angular/src/app/user-card-angular/user-card-angular.component.ts
import { Component, ElementRef, EventEmitter, Input, Output, ViewEncapsulation } from '@angular/core';

@Component({
  selector: 'user-card-angular',
  templateUrl: './user-card-angular.component.html',
  styleUrls: ['./user-card-angular.component.scss'],
  encapsulation: ViewEncapsulation.ShadowDom
})
export class UserCardAngularComponent {

  @Input() name: string;
  @Input() avatar: string;

  @Output() deleteAngular = new EventEmitter();

  showInfo = false;

  constructor(private el: ElementRef) { }

  toggleShowInfo() {
    this.showInfo = !this.showInfo;
  }

  deleteClick() {
    this.deleteAngular.emit();
  }
}

<div class="user-card">
  <img [src]="avatar" alt=""/>
  <div>
    <h3>{{name}}</h3>
    <p>Angular Web Component</p>
    <div class="info" [hidden]="!showInfo">
      <p><slot name="email"></slot></p>
    </div>
    <button id="toggle-info" (click)="toggleShowInfo()">{{this.showInfo ? 'Hide' : 'Show'}} Info</button>
    <button id="delete-btn" (click)="deleteClick()">Delete Me!</button>
  </div>
</div>

// build-components/stencil/src/components/user-card-stencil/user-card-stencil.tsx
import { Component, ComponentInterface, Host, h, Prop, State, Event, EventEmitter } from '@stencil/core';

@Component({
  tag: 'user-card-stencil',
  styleUrl: 'user-card-stencil.css',
  shadow: true
})
export class UserCardStencil implements ComponentInterface {

  @Prop() name: string;
  @Prop() avatar: string;

  @State() showInfo: boolean;

  @Event({
    eventName: 'deleteStencil',
    bubbles: true,
    cancelable: false,
    composed: true
  }) deleteClickStencil: EventEmitter;

  render() {
    return (
      <Host>
        <div class="user-card">
          <img src={this.avatar} alt="no-avatar" />
          <div>
            <h3>{this.name}</h3>
            <p>Stencil Web Component</p>
            <div class={{ 'info': true, 'hidden': !this.showInfo }}>
              <p><slot name="email" /></p>
            </div>
            <button id="toggle-info"
                    onClick={() => this.onToggleHideInfo()}>
              {this.showInfo ? 'Hide' : 'Show'} Info
            </button>
            <button id="delete-btn" onClick={() => this.onDeleteClick()}>Delete Me!</button>
          </div>
        </div>
      </Host>
    );
  }

  private onToggleHideInfo() {
    this.showInfo = !this.showInfo;
  }

  private onDeleteClick() {
    this.deleteClickStencil.emit();
  }

}
